/*
 * Copyright (C) 2012 Spatial Transcriptomics AB
 * Read LICENSE for more information about licensing terms
 * Contact: Jose Fernandez Navarro <jose.fernandez.navarro@scilifelab.se>
 */

package com.spatialtranscriptomics.controller;

import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.annotation.Secured;
import org.springframework.stereotype.Controller;
import org.springframework.stereotype.Repository;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.spatialtranscriptomics.exceptions.BadRequestResponse;
import com.spatialtranscriptomics.exceptions.CustomBadRequestException;
import com.spatialtranscriptomics.exceptions.CustomNotFoundException;
import com.spatialtranscriptomics.exceptions.NotFoundResponse;
import com.spatialtranscriptomics.model.PipelineStats;
import com.spatialtranscriptomics.serviceImpl.PipelineStatsServiceImpl;

/**
 * This class is Spring MVC controller class for the API endpoint "rest/pipelinestats". It implements the methods available at this endpoint.
 */

@Repository
@Controller
@RequestMapping("/rest/pipelinestats")
public class PipelineStatsController {

	@SuppressWarnings("unused")
	private static final Logger logger = Logger.getLogger(PipelineStatsController.class);

	@Autowired
	PipelineStatsServiceImpl pipelinestatsService;

	// list / get for experiment
	@Secured({"ROLE_CM","ROLE_ADMIN"})
	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody
	List<PipelineStats> list(@RequestParam(value = "experiment_id", required = false) String experimentId) {
		List<PipelineStats> pipelinestats = null;
		if (experimentId != null) {
			pipelinestats = new ArrayList<PipelineStats>(1);
			pipelinestats.add(pipelinestatsService.findByExperiment(experimentId));
		} else {
			pipelinestats = pipelinestatsService.list();
		}
		if (pipelinestats == null) {
			throw new CustomNotFoundException(
					"No PipelineStats found or you dont have permissions to access them.");
		}
		return pipelinestats;
	}
	

	// get
	@Secured({"ROLE_CM","ROLE_ADMIN"})
	@RequestMapping(value = "{id}", method = RequestMethod.GET)
	public @ResponseBody
	PipelineStats get(@PathVariable String id) {
		PipelineStats pipelinestats = pipelinestatsService.find(id);
		if (pipelinestats == null) {
			throw new CustomNotFoundException(
					"A PipelineStats with this ID does not exist or you dont have permissions to access it.");
		}
		return pipelinestats;
	}

	// add
	@Secured({"ROLE_CM","ROLE_ADMIN"})
	@RequestMapping(method = RequestMethod.POST)
	public @ResponseBody
	PipelineStats add(@RequestBody @Valid PipelineStats pipelinestats, BindingResult result) {
		// PipelineStats validation
		if (result.hasErrors()) {
			// TODO send error messages here
			throw new CustomBadRequestException(
					"PipelineStats is invalid. Missing required fields?");
		}
		if (pipelinestats.getId() != null) {
			throw new CustomBadRequestException(
					"The PipelineStats you want to add must not have an ID. The ID will be autogenerated.");
		}
		if (pipelinestatsService.findByExperiment(pipelinestats.getExperiment_id()) != null) {
			throw new CustomBadRequestException(
					"An PipelineStats for this PipelineExperiment already exists.");
		}
		return pipelinestatsService.add(pipelinestats);
	}

	// update
	@Secured({"ROLE_CM","ROLE_ADMIN"})
	@RequestMapping(value = "{id}", method = RequestMethod.PUT)
	public @ResponseBody
	void update(@PathVariable String id, @RequestBody @Valid PipelineStats pipelinestats, BindingResult result) {

		// PipelineStats validation
		if (result.hasErrors()) {
			// TODO send error messages here
			throw new CustomBadRequestException(
					"PipelineStats is invalid. Missing required fields?");
		}

		if (!id.equals(pipelinestats.getId())) {
			throw new CustomBadRequestException(
					"PipelineStats ID in request URL does not match ID in content body.");
		} else if (pipelinestatsService.find(id) == null) {
			throw new CustomBadRequestException(
					"A PipelineStats with this ID does not exist or you don't have permissions to access it.");
		} else {
			pipelinestatsService.update(pipelinestats);
		}
	}

	// delete
	@Secured({"ROLE_CM","ROLE_ADMIN"})
	@RequestMapping(value = "{id}", method = RequestMethod.DELETE)
	public @ResponseBody
	void delete(@PathVariable String id) {
		pipelinestatsService.delete(id);
	}

	@ExceptionHandler(CustomNotFoundException.class)
	@ResponseStatus(value = HttpStatus.NOT_FOUND)
	public @ResponseBody
	NotFoundResponse handleNotFoundException(CustomNotFoundException ex) {
		return new NotFoundResponse(ex.getMessage());
	}

	@ExceptionHandler(CustomBadRequestException.class)
	@ResponseStatus(value = HttpStatus.BAD_REQUEST)
	public @ResponseBody
	BadRequestResponse handleNotFoundException(CustomBadRequestException ex) {
		return new BadRequestResponse(ex.getMessage());
	}

}
