/*
 * Copyright (C) 2012 Spatial Transcriptomics AB
 * Read LICENSE for more information about licensing terms
 * Contact: Jose Fernandez Navarro <jose.fernandez.navarro@scilifelab.se>
 */
package com.spatialtranscriptomics.controller;

import com.spatialtranscriptomics.exceptions.BadRequestResponse;
import com.spatialtranscriptomics.exceptions.CustomBadRequestException;
import com.spatialtranscriptomics.exceptions.CustomInternalServerErrorException;
import com.spatialtranscriptomics.exceptions.CustomInternalServerErrorResponse;
import com.spatialtranscriptomics.exceptions.CustomNotFoundException;
import com.spatialtranscriptomics.exceptions.CustomNotModifiedException;
import com.spatialtranscriptomics.exceptions.NotFoundResponse;
import com.spatialtranscriptomics.exceptions.NotModifiedResponse;
import com.spatialtranscriptomics.model.LastModifiedDate;
import com.spatialtranscriptomics.model.Task;
import com.spatialtranscriptomics.serviceImpl.TaskServiceImpl;
import java.util.List;
import javax.validation.Valid;
import org.apache.log4j.Logger;
import org.joda.time.DateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.annotation.Secured;
import org.springframework.stereotype.Controller;
import org.springframework.stereotype.Repository;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 * This class is Spring MVC controller class for the API endpoint "rest/task".
 * It implements the methods available at this endpoint.
 */
@Repository
@Controller
@RequestMapping("/rest/task")
public class TaskController {

    @SuppressWarnings("unused")
    private static final Logger logger = Logger.getLogger(TaskController.class);

    @Autowired
    TaskServiceImpl taskService;

    // list / list for account
    @Secured({"ROLE_USER", "ROLE_CM", "ROLE_ADMIN"})
    @RequestMapping(method = {RequestMethod.GET, RequestMethod.HEAD})
    public @ResponseBody
    List<Task> list(@RequestParam(value = "account", required = false) String accountId) {
        List<Task> tasks = null;
        if (accountId != null) {
            tasks = taskService.findByAccount(accountId);
        } else {
            tasks = taskService.list();
        }
        if (tasks == null) {
            throw new CustomNotFoundException("No tasks found or you dont have permissions to access them.");
        }
        return tasks;
    }

    // get
    @Secured({"ROLE_CM", "ROLE_ADMIN"})
    @RequestMapping(value = "{id}", method = {RequestMethod.GET, RequestMethod.HEAD})
    public @ResponseBody
    Task get(@PathVariable String id) {
        Task task = taskService.find(id);
        if (task == null) {
            throw new CustomNotFoundException("A task with this ID does not exist or you dont have permissions to access it.");
        }

        return task;
    }

    // get last modified
    @Secured({"ROLE_CM", "ROLE_ADMIN"})
    @RequestMapping(value = "/lastmodified/{id}", method = {RequestMethod.GET, RequestMethod.HEAD})
    public @ResponseBody
    LastModifiedDate getLastModified(@PathVariable String id) {
        Task task = taskService.find(id);
        if (task == null) {
            throw new CustomNotFoundException("A task with this ID does not exist or you dont have permissions to access it.");
        }
        return new LastModifiedDate(task.getLast_modified());
    }

    // add
    @Secured({"ROLE_CM", "ROLE_ADMIN"})
    @RequestMapping(method = RequestMethod.POST)
    public @ResponseBody
    Task add(@RequestBody @Valid Task task, BindingResult result) {
        // Task validation
        if (result.hasErrors()) {
            // TODO send error messages here
            throw new CustomBadRequestException("Task is invalid. Missing required fields?");
        }
        if (task.getId() != null) {
            throw new CustomBadRequestException("The task you want to add must not have an ID. The ID will be autogenerated.");
        }
        if (taskService.findByName(task.getName()) != null) {
            throw new CustomBadRequestException("An task with this name already exists. Task names are unique.");
        }
        return taskService.add(task);
    }

    // update
    @Secured({"ROLE_CM", "ROLE_ADMIN"})
    @RequestMapping(value = "{id}", method = RequestMethod.PUT)
    public @ResponseBody
    void update(@PathVariable String id, @RequestBody @Valid Task task,
            BindingResult result) {
        // Task validation
        if (result.hasErrors()) {
            // TODO send error messages here
            throw new CustomBadRequestException("Task is invalid. Missing required fields?");
        }
        if (!id.equals(task.getId())) {
            throw new CustomBadRequestException("Task ID in request URL does not match ID in content body.");
        } else if (taskService.find(id) == null) {
            throw new CustomBadRequestException("A task with this ID does not exist or you don't have permissions to access it.");
        } else {
            taskService.update(task);
        }
    }

    // delete
    @Secured({"ROLE_CM", "ROLE_ADMIN"})
    @RequestMapping(value = "{id}", method = RequestMethod.DELETE)
    public @ResponseBody
    void delete(@PathVariable String id) {
        taskService.delete(id);
    }

    @ExceptionHandler(CustomNotModifiedException.class)
    @ResponseStatus(value = HttpStatus.NOT_MODIFIED)
    public @ResponseBody
    NotModifiedResponse handleNotModifiedException(CustomNotModifiedException ex) {
        return new NotModifiedResponse(ex.getMessage());
    }

    @ExceptionHandler(CustomNotFoundException.class)
    @ResponseStatus(value = HttpStatus.NOT_FOUND)
    public @ResponseBody
    NotFoundResponse handleNotFoundException(CustomNotFoundException ex) {
        return new NotFoundResponse(ex.getMessage());
    }

    @ExceptionHandler(CustomBadRequestException.class)
    @ResponseStatus(value = HttpStatus.BAD_REQUEST)
    public @ResponseBody
    BadRequestResponse handleBadRequestException(CustomBadRequestException ex) {
        return new BadRequestResponse(ex.getMessage());
    }

    @ExceptionHandler(RuntimeException.class)
    @ResponseStatus(value = HttpStatus.INTERNAL_SERVER_ERROR)
    public @ResponseBody
    CustomInternalServerErrorResponse handleRuntimeException(CustomInternalServerErrorException ex) {
        logger.error("Unknown error in task controller: " + ex.getMessage());
        return new CustomInternalServerErrorResponse(ex.getMessage());
    }

}
